version: '3'

services:
  app:
    build: .
    container_name: messenger
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - messenger

networks:
  messenger:
